### ISSUE TITLE
Bot launch error

### ISSUE THREAD

**Issue by Smerch19** [Desamod/TrustAppBot#2]
In .env  
API_ID and API_HASH
Filled.
Python version 3.12.5

> Starting the bot...
Traceback (most recent call last):
  File "D:\0_Proger\Bots\TrustAppBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\0_Proger\Bots\TrustAppBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\0_Proger\Bots\TrustAppBot\bot\utils\launcher.py", line 13, in <module>
    from bot.core.tapper import run_tapper
  File "D:\0_Proger\Bots\TrustAppBot\bot\core\tapper.py", line 7, in <module>
    from aiocfscrape import CloudflareScraper
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\0_Proger\Bots\TrustAppBot\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
done
PLEASE EDIT .ENV FILE

**Comment by Desamod** [comment]
Use [python](https://www.python.org/downloads/) version 3.10
